"""The signals card. Public -- the Telegram page renders it too."""
from nicegui import ui
from backend.src.controllers import trading_controller as trading_ctl
from backend.src.controllers import sync_controller as sync_ctl


def render_signals_card() -> None:
    """Per-source live-execution toggles (Telegram/Bounce/Breakout/Reversal Engine) --
    self-contained, importable by other pages (moved to the top of the
    Parsing page, 2026-07-22 -- was previously part of Trading > Strategy)."""
    rs = trading_ctl.get_risk_settings()
    with ui.card().classes("w-full bg-gray-800 p-4 rounded-lg"):
        ui.label("Signals").classes("text-base font-bold text-yellow-300 mb-3")

        with ui.row().classes("w-full gap-6 flex-wrap items-start"):

            # ── Telegram Signals ──────────────────────────────────────────
            with ui.column().classes("gap-1 min-w-52"):
                with ui.row().classes("items-center gap-1"):
                    ui.label("Telegram Signals").classes("text-sm font-semibold text-gray-200")
                    ui.icon("info_outline", size="xs").classes("text-blue-400 cursor-help").tooltip(
                        "When ON, Telegram signals from your configured channels are parsed "
                        "and can be auto-executed. When OFF, incoming Telegram messages are "
                        "collected but completely ignored — no signals are created or traded."
                    )
                ui.label("Accept and trade signals from Telegram channels").classes(
                    "text-xs text-gray-500 mb-1"
                )
                _tg_on = bool(rs.get("accept_tg_signals", 1))
                tg_sig_badge = ui.badge(
                    "TG SIGNALS ON" if _tg_on else "TG SIGNALS OFF",
                    color="green" if _tg_on else "grey",
                )

                def toggle_tg_signals(badge=tg_sig_badge):
                    cur = bool(trading_ctl.get_risk_settings().get("accept_tg_signals", 1))
                    trading_ctl.update_risk_settings({"accept_tg_signals": 0 if cur else 1})
                    new = not cur
                    badge.props(f"color={'green' if new else 'grey'}")
                    badge.text = "TG SIGNALS ON" if new else "TG SIGNALS OFF"
                    ui.notify(
                        "Telegram signals enabled" if new else "Telegram signals disabled — incoming messages will be ignored",
                        type="positive" if new else "warning",
                    )

                ui.button("Toggle", icon="swap_horiz", on_click=toggle_tg_signals).classes(
                    "text-xs mt-1"
                )

            ui.separator().props("vertical").classes("hidden sm:block")

            # ── Bounce Generator ──────────────────────────────────────────
            with ui.column().classes("gap-1 min-w-52"):
                with ui.row().classes("items-center gap-1"):
                    ui.label("Bounce Generator").classes("text-sm font-semibold text-gray-200")
                    ui.icon("info_outline", size="xs").classes("text-blue-400 cursor-help").tooltip(
                        "When ON, signals generated by the Bounce Generator are "
                        "executed as real MT5 trades using the active strategy and risk settings. "
                        "When OFF, generated signals remain virtual only. "
                        "Use Bounce Generator tab to start/stop the engine itself."
                    )
                ui.label("Route bounce signals to MT5").classes(
                    "text-xs text-gray-500 mb-1"
                )
                _sg_on = bool(rs.get("sg_live_execution", 0))
                sg_live_badge = ui.badge(
                    "SG LIVE ON" if _sg_on else "SG LIVE OFF",
                    color="green" if _sg_on else "grey",
                )

                def toggle_sg_live(badge=sg_live_badge):
                    cur = bool(trading_ctl.get_risk_settings().get("sg_live_execution", 0))
                    new = not cur
                    trading_ctl.update_risk_settings({"sg_live_execution": 1 if new else 0})
                    badge.props(f"color={'green' if new else 'grey'}")
                    badge.text = "SG LIVE ON" if new else "SG LIVE OFF"
                    ui.notify(
                        "Bounce Generator live execution ON — signals will place real MT5 trades"
                        if new else "Bounce Generator live execution OFF",
                        type="positive" if new else "info",
                    )

                ui.button("Toggle", icon="swap_horiz", on_click=toggle_sg_live).classes(
                    "text-xs mt-1"
                )

                ui.separator().classes("my-1")
                ui.label("AI signal evaluation").classes("text-xs text-gray-500 mb-1")
                _sg_claude_on = bool(rs.get("sg_claude_eval_enabled", 1))
                sg_claude_badge = ui.badge(
                    "AI ON" if _sg_claude_on else "AI OFF",
                    color="blue" if _sg_claude_on else "grey",
                )

                async def toggle_sg_claude(badge=sg_claude_badge):
                    key = "sg_claude_eval_enabled"
                    if sync_ctl.is_remote_active():
                        # Read "current" from the VPS's own confirmed settings
                        # snapshot, not this node's local DB row — the RPC below
                        # never updates that local row, only the periodic full
                        # settings broadcast does, so basing "current" on the
                        # local row made every click here recompute the same
                        # "new" value forever (toggle stuck one-directional:
                        # confirmed live — Bounce stuck OFF, Breakout stuck ON,
                        # each click just re-sent the same target state).
                        cur = bool(sync_ctl.link_state()["remote_settings"].get(key, 1))
                        new = not cur
                        try:
                            ack = await sync_ctl.send_engine_control("bounce", "set_ai_eval", enabled=new)
                        except Exception as exc:
                            ui.notify(f"Failed to reach VPS: {exc}", type="negative")
                            return
                        if ack.get("error"):
                            ui.notify(f"VPS rejected: {ack['error']}", type="negative")
                            return
                        sync_ctl.note_remote_setting(key, 1 if new else 0)
                    else:
                        cur = bool(trading_ctl.get_risk_settings().get(key, 1))
                        new = not cur
                        trading_ctl.update_risk_settings({key: 1 if new else 0})
                    badge.props(f"color={'blue' if new else 'grey'}")
                    badge.text = "AI ON" if new else "AI OFF"
                    ui.notify(
                        "Bounce: AI evaluation ON — each signal reviewed by AI"
                        if new else
                        "Bounce: AI evaluation OFF — ML + rules only (faster)",
                        type="info",
                    )

                ui.button("Toggle", icon="psychology", on_click=toggle_sg_claude).classes(
                    "text-xs mt-1"
                )

            ui.separator().props("vertical").classes("hidden sm:block")

            # ── Breakout Generator ────────────────────────────────────────
            with ui.column().classes("gap-1 min-w-52"):
                with ui.row().classes("items-center gap-1"):
                    ui.label("Breakout Generator").classes("text-sm font-semibold text-gray-200")
                    ui.icon("info_outline", size="xs").classes("text-blue-400 cursor-help").tooltip(
                        "When ON, confirmed breakout signals are sent to MT5 as live trades. "
                        "When OFF, the engine runs in virtual/learning-only mode. "
                        "Use Breakout Generator tab to start/stop the engine and view signals."
                    )
                ui.label("Route breakout signals to MT5 as live trades").classes(
                    "text-xs text-gray-500 mb-1"
                )
                _bo_live_on = bool(rs.get("bo_live_execution", 0))
                bo_live_badge = ui.badge(
                    "BO LIVE ON" if _bo_live_on else "BO LIVE OFF",
                    color="green" if _bo_live_on else "grey",
                )

                def toggle_bo_live(badge=bo_live_badge):
                    cur = bool(trading_ctl.get_risk_settings().get("bo_live_execution", 0))
                    new = not cur
                    trading_ctl.update_risk_settings({"bo_live_execution": 1 if new else 0})
                    badge.props(f"color={'green' if new else 'grey'}")
                    badge.text = "BO LIVE ON" if new else "BO LIVE OFF"
                    ui.notify(
                        "Breakout live execution ENABLED — signals will open real MT5 trades" if new
                        else "Breakout live execution DISABLED — virtual mode only",
                        type="positive" if new else "warning",
                    )

                # Sync badge to live state on each page refresh (30s timer)
                async def _sync_bo_badge(badge=bo_live_badge):
                    # async: get_risk_settings() is a synchronous SQLite read, and a
                    # sync timer callback would do it on the event loop.
                    _rs = await trading_ctl.get_risk_settings_async()
                    _live = bool(_rs.get("bo_live_execution", 0))
                    badge.text = "BO LIVE ON" if _live else "BO LIVE OFF"
                    badge.props(f"color={'green' if _live else 'grey'}")
                ui.timer(30, _sync_bo_badge)

                ui.button("Toggle", icon="swap_horiz", on_click=toggle_bo_live).classes(
                    "text-xs mt-1"
                )

                ui.separator().classes("my-1")
                ui.label("AI signal evaluation").classes("text-xs text-gray-500 mb-1")
                _bo_claude_on = bool(rs.get("bo_claude_eval_enabled", 1))
                bo_claude_badge = ui.badge(
                    "AI ON" if _bo_claude_on else "AI OFF",
                    color="blue" if _bo_claude_on else "grey",
                )

                async def toggle_bo_claude(badge=bo_claude_badge):
                    key = "bo_claude_eval_enabled"
                    if sync_ctl.is_remote_active():
                        # See toggle_sg_claude's comment above — "current" must
                        # come from the VPS's confirmed settings snapshot, not
                        # this node's local DB row, or the toggle sticks in one
                        # direction forever.
                        cur = bool(sync_ctl.link_state()["remote_settings"].get(key, 1))
                        new = not cur
                        try:
                            ack = await sync_ctl.send_engine_control("breakout", "set_ai_eval", enabled=new)
                        except Exception as exc:
                            ui.notify(f"Failed to reach VPS: {exc}", type="negative")
                            return
                        if ack.get("error"):
                            ui.notify(f"VPS rejected: {ack['error']}", type="negative")
                            return
                        sync_ctl.note_remote_setting(key, 1 if new else 0)
                    else:
                        cur = bool(trading_ctl.get_risk_settings().get(key, 1))
                        new = not cur
                        trading_ctl.update_risk_settings({key: 1 if new else 0})
                    badge.props(f"color={'blue' if new else 'grey'}")
                    badge.text = "AI ON" if new else "AI OFF"
                    ui.notify(
                        "Breakout: AI evaluation ON — each signal reviewed by AI"
                        if new else
                        "Breakout: AI evaluation OFF — ML + rules only (faster execution)",
                        type="info",
                    )

                ui.button("Toggle", icon="psychology", on_click=toggle_bo_claude).classes(
                    "text-xs mt-1"
                )

            ui.separator().props("vertical").classes("hidden sm:block")

            # ── Reversal Engine ────────────────────────────────────────────
            with ui.column().classes("gap-1 min-w-52"):
                with ui.row().classes("items-center gap-1"):
                    ui.label("Reversal Engine").classes("text-sm font-semibold text-gray-200")
                    ui.icon("info_outline", size="xs").classes("text-blue-400 cursor-help").tooltip(
                        "When ON, signals generated by the Reversal Engine are executed as "
                        "real MT5 trades. The engine reverse-engineers Gold Diggers VIP's "
                        "methodology to generate signals before they arrive on Telegram. "
                        "Use Signal Generator > Reversal Engine tab to view signals and correlation stats."
                    )
                ui.label("Route Reversal Engine signals to MT5 as live trades").classes(
                    "text-xs text-gray-500 mb-1"
                )
                _re_live_on = bool(rs.get("re_live_execution", 0))
                re_live_badge = ui.badge(
                    "RE LIVE ON" if _re_live_on else "RE LIVE OFF",
                    color="green" if _re_live_on else "grey",
                )

                def toggle_re_live(badge=re_live_badge):
                    cur = bool(trading_ctl.get_risk_settings().get("re_live_execution", 0))
                    new = not cur
                    trading_ctl.update_risk_settings({"re_live_execution": 1 if new else 0})
                    badge.props(f"color={'green' if new else 'grey'}")
                    badge.text = "RE LIVE ON" if new else "RE LIVE OFF"
                    ui.notify(
                        "Reversal Engine live execution ENABLED — signals will open real MT5 trades" if new
                        else "Reversal Engine live execution DISABLED — virtual mode only",
                        type="positive" if new else "warning",
                    )

                async def _sync_re_badge(badge=re_live_badge):
                    # async: get_risk_settings() is a synchronous SQLite read, and a
                    # sync timer callback would do it on the event loop.
                    _rs = await trading_ctl.get_risk_settings_async()
                    _live = bool(_rs.get("re_live_execution", 0))
                    badge.text = "RE LIVE ON" if _live else "RE LIVE OFF"
                    badge.props(f"color={'green' if _live else 'grey'}")
                ui.timer(30, _sync_re_badge)

                ui.button("Toggle", icon="swap_horiz", on_click=toggle_re_live).classes(
                    "text-xs mt-1"
                )
